# Generated by Django 4.2.8 on 2023-12-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charities',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='charities',
            name='donation_goal',
        ),
        migrations.AddField(
            model_name='charities',
            name='address',
            field=models.CharField(default='22 Bellgrove Junction', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charities',
            name='country',
            field=models.CharField(default='France', max_length=255),
            preserve_default=False,
        ),
    ]
